[Reland][Inductor] Prune configs that require more shared memory than the hardware limit
Summary:
This is a re-land of [PR161040](https://github.com/pytorch/pytorch/pull/161040), which had previously caused test failures on AMD GPUs. The tests are now configured to target only NVIDIA GPUs.
This diff removes configurations that exceed the hardware shared memory limit, which causes the following compilation error:
```
No valid triton configs. OutOfMemoryError: out of resource: triton_mm Required: 327680 Hardware limit:232448 Reducing block sizes or `num_stages` may help.
```

Test Plan:

```
(pytorch-3.12) bash-5.1$ pytest -k test_max_autotune_prune_choices test/inductor/test_max_autotune.py ^C
(pytorch-3.12) bash-5.1$ pytest -k test_prune_configs_over_shared_memory_limit test/inductor/test_triton_heuristics.py
```

Tags: ghstack-source-id: 22d49762227b5d6557a8888344610483ddf7e499
Pull Request resolved: https://github.com/pytorch/pytorch/pull/161816
ghstack-source-id: 8cdd46f9a89bc831e2f8460f30a6ae03611266a3